# Using Historical Data to Predict Batting Success: Step 2 Data Prep

Authored by: Donna J. Harris (994042890)

Email: harr2890@mylaurier.ca

For: CP640 Machine Learning (S22) with Professor Elham Harirpoush

## Step 2 of Data Preparation   TODO

Step 2 ... means we've done the first part that is common to all work, and now we're ready to experiment specifically from this point with other data formats...

TODO....

## Environment Setup

Import and establish environment for initial work, including showing all dataframe column values.

In [115]:
import pandas as pd

pd.set_option('display.max_columns', None)

Load in the two stored data files: `./data/core_mlb_dataset.csv` and `./data/hof_dataset.csv` so we can continue with pre-processing the data.

In [116]:
core_mlb_dataset = "./data/core_mlb_dataset.csv"
df = pd.read_csv(core_mlb_dataset)
df

,ID,Player,Tm,Opp,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,HBP,SH,SF,Result,Season
0,delahed01,Ed Delahanty,PHI,BRO,5,4,1,2,0,0,0,0,1,0,0,0,0,L,1901
1,dolanjo02,Joe Dolan,PHI,BRO,5,5,0,1,0,0,0,1,0,0,0,0,0,L,1901
2,childcu01,Cupid Childs,CHC,STL,5,5,1,1,0,0,0,0,0,0,0,0,0,W,1901
3,crolifr01,Fred Crolius,BSN,NYG,4,4,0,0,0,0,0,1,0,0,0,0,0,W,1901
4,delahed01,Ed Delahanty,PHI,BRO,4,4,0,0,0,0,0,0,0,2,0,0,0,L,1901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3715517,woodfja01,Jake Woodford,STL,CHC,2,1,0,0,0,0,0,0,0,0,0,1,0,L,2021
3715518,yastrmi01,Mike Yastrzemski,SFG,SDP,4,3,1,1,1,0,0,2,1,1,0,0,0,W,2021
3715519,zimmebr01,Bradley Zimmer,CLE,TEX,4,4,1,2,0,0,0,1,0,0,0,0,0,W,2021
3715520,zimmery01,Ryan Zimmerman,WSN,BOS,4,3,0,0,0,0,0,1,1,2,0,0,0,L,2021
3715521,zuninmi01,Mike Zunino,TBR,NYY,4,4,0,0,0,0,0,0,0,1,0,0,0,L,2021

In [117]:
hof_dataset = "./data/hof_dataset.csv"
hof = pd.read_csv(hof_dataset)
hof

            ID  Inductee
0    hodgegi01         1
1     kaatji01         1
2    minosmi01         1
3    olivato01         1
4    ortizda01         1
..         ...       ...
263   cobbty01         1
264  johnswa01         1
265  mathech01         1
266   ruthba01         1
267  wagneho01         1

[268 rows x 2 columns]

## Preprocessing - Continued

### Looking at Player Data

So far, we've looked at data from the perspective of each individual game played by an individual player. Now the data is healthier than when we started, we want to look at individual players during their careers.

Keeping in mind that our goal is to find trends that might predict a batter's success in the future, we will want to be able to combine their statistics over time. It might also be useful to attempt to find ways to examine their data during parts of their careers, but that's not currently a focus

In [118]:
print("There are",len(pd.unique(df['ID'])),"unique players remaining in this dataset.")

There are 14336 unique players remaining in this dataset.

In [119]:
columns = ['ID', 'Player','PA','AB','R','H','2B','3B','HR','RBI','BB','SO','HBP','SH', 'SF']
summables = ['PA','AB','R','H','2B','3B','HR','RBI','BB','SO','HBP','SH', 'SF']

career = df.copy()
career = career[columns].copy()
career

,ID,Player,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,HBP,SH,SF
0,delahed01,Ed Delahanty,5,4,1,2,0,0,0,0,1,0,0,0,0
1,dolanjo02,Joe Dolan,5,5,0,1,0,0,0,1,0,0,0,0,0
2,childcu01,Cupid Childs,5,5,1,1,0,0,0,0,0,0,0,0,0
3,crolifr01,Fred Crolius,4,4,0,0,0,0,0,1,0,0,0,0,0
4,delahed01,Ed Delahanty,4,4,0,0,0,0,0,0,0,2,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3715517,woodfja01,Jake Woodford,2,1,0,0,0,0,0,0,0,0,0,1,0
3715518,yastrmi01,Mike Yastrzemski,4,3,1,1,1,0,0,2,1,1,0,0,0
3715519,zimmebr01,Bradley Zimmer,4,4,1,2,0,0,0,1,0,0,0,0,0
3715520,zimmery01,Ryan Zimmerman,4,3,0,0,0,0,0,1,1,2,0,0,0
3715521,zuninmi01,Mike Zunino,4,4,0,0,0,0,0,0,0,1,0,0,0

In [120]:
career = career.groupby(['ID', 'Player'])
career = career[summables].sum().copy()
career

,,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,HBP,SH,SF
ID,Player,,,,,,,,,,,,,
aardsda01,David Aardsma,5,4,0,0,0,0,0,0,0,2,0,1,0
aaronha01,Henry Aaron,13666,12121,2128,3703,614,96,740,2243,1372,1357,32,21,120
aaronto01,Tommie Aaron,1045,944,99,216,42,6,13,94,85,145,0,9,6
aasedo01,Don Aase,5,5,0,0,0,0,0,0,0,3,0,0,0
abadan01,Andy Abad,25,21,1,2,0,0,0,0,4,5,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zuninmi01,Mike Zunino,2835,2559,308,518,111,5,141,345,198,981,58,8,12
zupcibo01,Bob Zupcic,886,795,93,199,47,4,7,80,57,137,6,20,8
zupofr01,Frank Zupo,8,7,1,2,1,0,0,0,1,2,0,0,0
zuvelpa01,Paul Zuvella,545,491,40,109,17,2,2,20,34,50,2,18,0
zuverge01,George Zuverink,156,133,4,19,2,1,0,7,7,36,0,16,0

**Note:** Now we've created our career statistics records for every player, we want to remove any records with 0 At Bats. We know that these players will not be in the Hall of Fame and it will avoid problems with calculating other statistics later.

In [121]:
career = career[career['AB'] > 0].copy()
career

,,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,HBP,SH,SF
ID,Player,,,,,,,,,,,,,
aardsda01,David Aardsma,5,4,0,0,0,0,0,0,0,2,0,1,0
aaronha01,Henry Aaron,13666,12121,2128,3703,614,96,740,2243,1372,1357,32,21,120
aaronto01,Tommie Aaron,1045,944,99,216,42,6,13,94,85,145,0,9,6
aasedo01,Don Aase,5,5,0,0,0,0,0,0,0,3,0,0,0
abadan01,Andy Abad,25,21,1,2,0,0,0,0,4,5,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zuninmi01,Mike Zunino,2835,2559,308,518,111,5,141,345,198,981,58,8,12
zupcibo01,Bob Zupcic,886,795,93,199,47,4,7,80,57,137,6,20,8
zupofr01,Frank Zupo,8,7,1,2,1,0,0,0,1,2,0,0,0
zuvelpa01,Paul Zuvella,545,491,40,109,17,2,2,20,34,50,2,18,0
zuverge01,George Zuverink,156,133,4,19,2,1,0,7,7,36,0,16,0

### Different Statistical Formulae

singles (int) = H - (2B + 3B + HR)

total_bases (int) = 1 * singles + 2 * 2B + 3 * 3B + 4 * HR


**AVG (float) = H / AB**

SLG (float) = total_bases / AB

OBP (float) = (H + BB + HBP)/(AB + BB + HBP + SF)

**OPS (float) = SLG + OBP**
https://en.wikipedia.org/wiki/On-base_plus_slugging  *** Reference is great for testing against

RC (float) = total_bases * ( (H + BB) / (AB + BB) )

ISO (float) = (1 * 2B + 2 * 3B + 3 * HR) / AB

PA/SO (float) = PA/SO

#### Simplification of SLG formula??

SLG = ( 1 * (H - (2B + 3B + HR)) + 2 * 2B + 3 * 3B + 4 * HR ) / AB
( H - 2B - 3B - HR + 2 * 2B + 3 * 3B + 4 * HR ) / AB
( H - 2B + 2 * 2B - 3B + 3 * 3B - HR + 4 * HR ) / AB
( H + 2B + 2 * 3B + 3 * HR ) / AB

In [122]:
career['AVG'] = career['H'] / (career['AB']*1.0)

career['SLG'] = (career['H'] + career['2B'] + 2*career['3B'] + 3*career['HR']) / (career['AB']*1.0)

career['OBP'] = (career['H'] + career['BB'] + career['HBP']) / ((career['AB'] + career['BB'] + career['HBP'] + career['SF'])*1.0) 

career['OPS'] = career['SLG'] + career['OBP']

career

,,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,HBP,SH,SF,AVG,SLG,OBP,OPS
ID,Player,,,,,,,,,,,,,,,,,
aardsda01,David Aardsma,5,4,0,0,0,0,0,0,0,2,0,1,0,0.000000,0.000000,0.000000,0.000000
aaronha01,Henry Aaron,13666,12121,2128,3703,614,96,740,2243,1372,1357,32,21,120,0.305503,0.555152,0.374276,0.929429
aaronto01,Tommie Aaron,1045,944,99,216,42,6,13,94,85,145,0,9,6,0.228814,0.327331,0.290821,0.618152
aasedo01,Don Aase,5,5,0,0,0,0,0,0,0,3,0,0,0,0.000000,0.000000,0.000000,0.000000
abadan01,Andy Abad,25,21,1,2,0,0,0,0,4,5,0,0,0,0.095238,0.095238,0.240000,0.335238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
zuninmi01,Mike Zunino,2835,2559,308,518,111,5,141,345,198,981,58,8,12,0.202423,0.415006,0.273788,0.688794
zupcibo01,Bob Zupcic,886,795,93,199,47,4,7,80,57,137,6,20,8,0.250314,0.345912,0.302540,0.648452
zupofr01,Frank Zupo,8,7,1,2,1,0,0,0,1,2,0,0,0,0.285714,0.428571,0.375000,0.803571
zuvelpa01,Paul Zuvella,545,491,40,109,17,2,2,20,34,50,2,18,0,0.221996,0.276986,0.275142,0.552128
zuverge01,George Zuverink,156,133,4,19,2,1,0,7,7,36,0,16,0,0.142857,0.172932,0.185714,0.358647

### Merging with Hall of Fame Data

In [123]:
career = pd.merge(hof, career, on="ID", how="right")
career

,ID,Inductee,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,HBP,SH,SF,AVG,SLG,OBP,OPS
0,aardsda01,NaN,5,4,0,0,0,0,0,0,0,2,0,1,0,0.000000,0.000000,0.000000,0.000000
1,aaronha01,1.0,13666,12121,2128,3703,614,96,740,2243,1372,1357,32,21,120,0.305503,0.555152,0.374276,0.929429
2,aaronto01,NaN,1045,944,99,216,42,6,13,94,85,145,0,9,6,0.228814,0.327331,0.290821,0.618152
3,aasedo01,NaN,5,5,0,0,0,0,0,0,0,3,0,0,0,0.000000,0.000000,0.000000,0.000000
4,abadan01,NaN,25,21,1,2,0,0,0,0,4,5,0,0,0,0.095238,0.095238,0.240000,0.335238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14259,zuninmi01,NaN,2835,2559,308,518,111,5,141,345,198,981,58,8,12,0.202423,0.415006,0.273788,0.688794
14260,zupcibo01,NaN,886,795,93,199,47,4,7,80,57,137,6,20,8,0.250314,0.345912,0.302540,0.648452
14261,zupofr01,NaN,8,7,1,2,1,0,0,0,1,2,0,0,0,0.285714,0.428571,0.375000,0.803571
14262,zuvelpa01,NaN,545,491,40,109,17,2,2,20,34,50,2,18,0,0.221996,0.276986,0.275142,0.552128
14263,zuverge01,NaN,156,133,4,19,2,1,0,7,7,36,0,16,0,0.142857,0.172932,0.185714,0.358647

In [124]:
hof_is_nan = career.loc[pd.isna(career['Inductee'])]
series_of_hof = hof_is_nan.index
career.loc[series_of_hof, 'Inductee'] = 0
career['Inductee'] = career['Inductee'].astype(int)
career

,ID,Inductee,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,HBP,SH,SF,AVG,SLG,OBP,OPS
0,aardsda01,0,5,4,0,0,0,0,0,0,0,2,0,1,0,0.000000,0.000000,0.000000,0.000000
1,aaronha01,1,13666,12121,2128,3703,614,96,740,2243,1372,1357,32,21,120,0.305503,0.555152,0.374276,0.929429
2,aaronto01,0,1045,944,99,216,42,6,13,94,85,145,0,9,6,0.228814,0.327331,0.290821,0.618152
3,aasedo01,0,5,5,0,0,0,0,0,0,0,3,0,0,0,0.000000,0.000000,0.000000,0.000000
4,abadan01,0,25,21,1,2,0,0,0,0,4,5,0,0,0,0.095238,0.095238,0.240000,0.335238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14259,zuninmi01,0,2835,2559,308,518,111,5,141,345,198,981,58,8,12,0.202423,0.415006,0.273788,0.688794
14260,zupcibo01,0,886,795,93,199,47,4,7,80,57,137,6,20,8,0.250314,0.345912,0.302540,0.648452
14261,zupofr01,0,8,7,1,2,1,0,0,0,1,2,0,0,0,0.285714,0.428571,0.375000,0.803571
14262,zuvelpa01,0,545,491,40,109,17,2,2,20,34,50,2,18,0,0.221996,0.276986,0.275142,0.552128
14263,zuverge01,0,156,133,4,19,2,1,0,7,7,36,0,16,0,0.142857,0.172932,0.185714,0.358647

In [125]:
name_cols = ['ID', 'Player']
names = df.copy()
names = names[name_cols].copy()
names = names.drop_duplicates(subset=['ID', 'Player'], keep='first')
names

                ID              Player
0        delahed01        Ed Delahanty
1        dolanjo02           Joe Dolan
2        childcu01        Cupid Childs
3        crolifr01        Fred Crolius
5        demonge01  Gene DeMontreville
...            ...                 ...
3715012  houckta01        Tanner Houck
3715063  minteaj01         A.J. Minter
3715191   adonjo01           Joan Adon
3715410  paynety01         Tyler Payne
3715474  stridsp01     Spencer Strider

[14336 rows x 2 columns]

In [126]:
career = pd.merge(names, career, on="ID", how="right")
career

,ID,Player,Inductee,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,HBP,SH,SF,AVG,SLG,OBP,OPS
0,aardsda01,David Aardsma,0,5,4,0,0,0,0,0,0,0,2,0,1,0,0.000000,0.000000,0.000000,0.000000
1,aaronha01,Henry Aaron,1,13666,12121,2128,3703,614,96,740,2243,1372,1357,32,21,120,0.305503,0.555152,0.374276,0.929429
2,aaronto01,Tommie Aaron,0,1045,944,99,216,42,6,13,94,85,145,0,9,6,0.228814,0.327331,0.290821,0.618152
3,aasedo01,Don Aase,0,5,5,0,0,0,0,0,0,0,3,0,0,0,0.000000,0.000000,0.000000,0.000000
4,abadan01,Andy Abad,0,25,21,1,2,0,0,0,0,4,5,0,0,0,0.095238,0.095238,0.240000,0.335238
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14259,zuninmi01,Mike Zunino,0,2835,2559,308,518,111,5,141,345,198,981,58,8,12,0.202423,0.415006,0.273788,0.688794
14260,zupcibo01,Bob Zupcic,0,886,795,93,199,47,4,7,80,57,137,6,20,8,0.250314,0.345912,0.302540,0.648452
14261,zupofr01,Frank Zupo,0,8,7,1,2,1,0,0,0,1,2,0,0,0,0.285714,0.428571,0.375000,0.803571
14262,zuvelpa01,Paul Zuvella,0,545,491,40,109,17,2,2,20,34,50,2,18,0,0.221996,0.276986,0.275142,0.552128
14263,zuverge01,George Zuverink,0,156,133,4,19,2,1,0,7,7,36,0,16,0,0.142857,0.172932,0.185714,0.358647

In [127]:
career = career[['ID', 'Player', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'AVG', 'SLG', 'OBP', 'OPS', 'Inductee']]
career

,ID,Player,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,AVG,SLG,OBP,OPS,Inductee
0,aardsda01,David Aardsma,5,4,0,0,0,0,0,0,0,2,0.000000,0.000000,0.000000,0.000000,0
1,aaronha01,Henry Aaron,13666,12121,2128,3703,614,96,740,2243,1372,1357,0.305503,0.555152,0.374276,0.929429,1
2,aaronto01,Tommie Aaron,1045,944,99,216,42,6,13,94,85,145,0.228814,0.327331,0.290821,0.618152,0
3,aasedo01,Don Aase,5,5,0,0,0,0,0,0,0,3,0.000000,0.000000,0.000000,0.000000,0
4,abadan01,Andy Abad,25,21,1,2,0,0,0,0,4,5,0.095238,0.095238,0.240000,0.335238,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14259,zuninmi01,Mike Zunino,2835,2559,308,518,111,5,141,345,198,981,0.202423,0.415006,0.273788,0.688794,0
14260,zupcibo01,Bob Zupcic,886,795,93,199,47,4,7,80,57,137,0.250314,0.345912,0.302540,0.648452,0
14261,zupofr01,Frank Zupo,8,7,1,2,1,0,0,0,1,2,0.285714,0.428571,0.375000,0.803571,0
14262,zuvelpa01,Paul Zuvella,545,491,40,109,17,2,2,20,34,50,0.221996,0.276986,0.275142,0.552128,0
14263,zuverge01,George Zuverink,156,133,4,19,2,1,0,7,7,36,0.142857,0.172932,0.185714,0.358647,0

In [163]:
all_sorted_by_ops = career.sort_values(by=['OPS'], ascending=False)
all_sorted_by_ops[all_sorted_by_ops['PA'] > 1999].head(50)

,ID,Player,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,AVG,SLG,OBP,OPS,Inductee
11194,ruthba01,Babe Ruth,10624,8400,2173,2872,506,137,714,2215,2063,1331,0.341905,0.689762,0.473925,1.163687,1
13864,willite01,Ted Williams,9598,7566,1768,2592,514,71,510,1806,1970,696,0.342585,0.631509,0.479516,1.111026,1
4464,gehrilo01,Lou Gehrig,9665,8001,1889,2721,534,164,493,1996,1512,795,0.340082,0.632671,0.447641,1.080312,1
1189,bondsba01,Barry Bonds,12606,9847,2226,2935,601,77,762,1996,2558,1539,0.298060,0.606885,0.444295,1.051180,0
4121,foxxji01,Jimmie Foxx,9676,8133,1751,2645,458,125,534,1919,1458,1311,0.325218,0.609246,0.428571,1.037818,1
4874,greenha01,Hank Greenberg,6098,5194,1047,1628,379,71,331,1274,853,846,0.313439,0.604929,0.411842,1.016771,1
13017,troutmi01,Mike Trout,5660,4656,966,1419,268,49,310,816,865,1215,0.304768,0.583119,0.418802,1.001920,0
10443,ramirma02,Manny Ramirez,9774,8244,1544,2574,547,20,555,1831,1329,1813,0.312227,0.585395,0.410561,0.995956,0
8322,mcgwima01,Mark McGwire,7660,6187,1166,1626,252,6,583,1414,1317,1596,0.262809,0.588169,0.394149,0.982318,0
12125,sotoju01,Juan Soto,2003,1612,337,485,91,8,98,312,373,352,0.300868,0.549628,0.431568,0.981196,0
3271,dimagjo01,Joe DiMaggio,7672,6821,1389,2215,390,131,361,1539,790,370,0.324732,0.579094,0.398459,0.977553,1
7858,mantlmi01,Mickey Mantle,9690,7924,1641,2351,332,69,528,1484,1694,1690,0.296694,0.555906,0.419285,0.975191,1
9105,musiast01,Stan Musial,12538,10820,1923,3573,716,176,467,1922,1579,691,0.330222,0.558410,0.416333,0.974744,1
12779,thomafr04,Frank Thomas,10075,8199,1494,2468,495,12,521,1704,1667,1397,0.301012,0.554946,0.419099,0.974044,1
13408,walkela01,Larry Walker,8030,6907,1352,2160,471,62,383,1311,913,1231,0.312726,0.565224,0.400224,0.965448,1
8734,mizejo01,Johnny Mize,7370,6442,1118,2011,367,84,359,1336,857,527,0.312170,0.562403,0.397225,0.959628,1
12797,thomeji01,Jim Thome,10313,8422,1583,2328,451,26,612,1699,1747,2548,0.276419,0.554144,0.401862,0.956006,1
5474,heltoto01,Todd Helton,9453,7962,1401,2519,592,37,369,1406,1335,1175,0.316378,0.539061,0.413994,0.953054,0
495,bagweje01,Jeff Bagwell,9431,7797,1517,2314,488,32,449,1529,1401,1558,0.296781,0.540336,0.407616,0.947952,1
9623,ottme01,Mel Ott,11348,9454,1856,2876,487,72,511,1870,1721,901,0.304210,0.533108,0.414717,0.947824,1
6726,kinerra01,Ralph Kiner,6256,5205,971,1451,216,39,369,1016,1011,754,0.278770,0.547935,0.397951,0.945886,1
927,berkmla01,Lance Berkman,7814,6491,1145,1905,422,30,366,1234,1201,1300,0.293483,0.536897,0.406042,0.942939,0
6479,judgeaa01,Aaron Judge,2465,2068,402,571,93,4,158,366,361,733,0.276112,0.554159,0.385708,0.939867,0
13903,wilsoha01,Hack Wilson,5555,4760,885,1460,266,67,244,1063,672,714,0.306723,0.544538,0.394718,0.939255,1
8144,mayswi01,Willie Mays,12217,10634,2013,3195,515,132,642,1864,1440,1504,0.300451,0.554824,0.383317,0.938141,1
13341,vottojo01,Joey Votto,8128,6722,1114,2027,435,21,331,1065,1294,1481,0.301547,0.520232,0.416462,0.936694,0
829,belleal01,Albert Belle,6676,5853,974,1726,389,21,381,1239,683,961,0.294892,0.563813,0.369471,0.933284,0
7959,martied01,Edgar Martinez,8674,7213,1219,2247,514,15,309,1261,1283,1202,0.311521,0.515458,0.417802,0.933260,1
5002,guerrvl01,Vladimir Guerrero,9059,8155,1328,2590,477,46,449,1496,737,985,0.317597,0.552544,0.378629,0.931173,1
9568,ortizda01,David Ortiz,10091,8640,1419,2472,632,19,541,1767,1319,1750,0.286111,0.551505,0.379522,0.931027,1
6381,jonesch06,Chipper Jones,10614,8984,1617,2726,549,38,468,1623,1512,1409,0.303428,0.529274,0.401093,0.930367,1
10911,rodrial01,Alex Rodriguez,12207,10566,2021,3115,548,31,696,2086,1338,2287,0.294814,0.550161,0.379706,0.929867,0
1,aaronha01,Henry Aaron,13666,12121,2128,3703,614,96,740,2243,1372,1357,0.305503,0.555152,0.374276,0.929429,1
3108,delgaca01,Carlos Delgado,8657,7283,1241,2038,483,18,473,1512,1109,1745,0.279830,0.545929,0.383389,0.929318,0
445,averiea01,Earl Averill,7221,6353,1222,2019,401,128,238,1165,780,520,0.317803,0.533606,0.395200,0.928806,1
6581,kellech01,Charlie Keller,4604,3790,726,1085,166,72,189,760,784,500,0.286280,0.517678,0.409904,0.927582,0
10878,robinfr02,Frank Robinson,11454,9748,1796,2855,514,71,571,1779,1396,1485,0.292881,0.535905,0.388670,0.924575,1
6783,kleinch01,Chuck Klein,7171,6487,1167,2076,398,74,300,1204,601,520,0.320025,0.542932,0.378820,0.921752,1
10084,piazzmi01,Mike Piazza,7745,6911,1048,2127,344,8,427,1335,759,1113,0.307770,0.545218,0.376501,0.921719,1
1810,cabremi01,Miguel Cabrera,10993,9625,1504,2987,597,17,502,1804,1199,1930,0.310338,0.532364,0.387241,0.919604,0
12055,snidedu01,Duke Snider,8021,6978,1224,2070,349,84,391,1298,941,1202,0.296647,0.538836,0.380379,0.919215,1
10332,pujolal01,Albert Pujols,12690,11114,1872,3301,672,16,679,2150,1345,1349,0.297013,0.543639,0.375049,0.918688,0
4513,giambja01,Jason Giambi,8908,7267,1227,2010,405,9,440,1441,1366,1572,0.276593,0.516444,0.399281,0.915726,0
5257,harpebr03,Bryce Harper,5482,4557,849,1273,270,22,267,752,833,1189,0.279350,0.524029,0.391590,0.915619,0
11835,simmoal01,Al Simmons,9519,8759,1507,2929,538,149,307,1843,619,744,0.334399,0.534993,0.380315,0.915307,1
5549,hermaba01,Babe Herman,6230,5604,882,1819,399,110,181,996,522,555,0.324590,0.531941,0.383249,0.915191,0
163,allendi01,Dick Allen,7315,6332,1098,1848,320,79,351,1119,894,1556,0.291851,0.533639,0.378067,0.911706,0
4659,goldspa01,Paul Goldschmidt,6300,5366,939,1572,341,22,280,927,837,1404,0.292956,0.521245,0.389313,0.910558,0
11493,schmimi01,Mike Schmidt,10062,8352,1506,2234,408,59,548,1595,1507,1883,0.267481,0.527299,0.380251,0.907550,1
4932,griffke02,Ken Griffey Jr.,11304,9801,1662,2781,524,38,630,1836,1312,1779,0.283747,0.537802,0.369511,0.907314,1

In [128]:
career[career['Inductee'] == 1 ]

,ID,Player,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,AVG,SLG,OBP,OPS,Inductee
1,aaronha01,Henry Aaron,13666,12121,2128,3703,614,96,740,2243,1372,1357,0.305503,0.555152,0.374276,0.929429,1
197,alomaro01,Roberto Alomar,10400,9073,1507,2724,504,80,210,1134,1032,1140,0.300231,0.442852,0.371245,0.814097,1
325,aparilu01,Luis Aparicio,10972,10003,1294,2610,383,91,80,770,713,718,0.260922,0.341398,0.309698,0.651095,1
331,applilu01,Luke Appling,10254,8856,1317,2750,441,101,45,1110,1313,531,0.310524,0.398374,0.400196,0.798570,1
395,ashburi01,Richie Ashburn,9442,8103,1286,2492,305,106,29,577,1169,553,0.307540,0.382081,0.396700,0.778780,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13903,wilsoha01,Hack Wilson,5555,4760,885,1460,266,67,244,1063,672,714,0.306723,0.544538,0.394718,0.939255,1
13949,winfida01,Dave Winfield,12358,11003,1669,3110,540,88,465,1833,1216,1686,0.282650,0.474507,0.352622,0.827129,1
14107,wynnea01,Early Wynn,1869,1675,135,361,59,5,17,174,138,323,0.215522,0.287164,0.275426,0.562590,1
14128,yastrca01,Carl Yastrzemski,13992,11988,1816,3419,646,59,452,1844,1845,1395,0.285202,0.462045,0.379453,0.841499,1
14196,yountro01,Robin Yount,12249,11008,1630,3142,583,126,251,1406,966,1350,0.285429,0.429688,0.342198,0.771886,1

In [151]:
hofers = career[career['Inductee'] == 1 ]

sorted_hofers = hofers.sort_values(by=['OPS'], ascending=True)

sorted_hofers.tail(60)

,ID,Player,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,AVG,SLG,OBP,OPS,Inductee
2134,cepedor01,Orlando Cepeda,8698,7927,1131,2351,417,27,379,1365,587,1165,0.296581,0.499432,0.349827,0.849260,1
13802,willibi01,Billy Williams,10519,9350,1410,2711,434,88,426,1474,1045,1047,0.289947,0.491872,0.361431,0.853303,1
10702,riceji01,Jim Rice,9058,8225,1249,2452,373,79,382,1451,670,1423,0.298116,0.502006,0.351928,0.853934,1
6512,kalinal01,Al Kaline,11335,9875,1582,2933,493,74,382,1530,1261,1000,0.297013,0.477975,0.376140,0.854115,1
7865,manushe01,Heinie Manush,8420,7658,1287,2525,492,160,110,1174,506,346,0.329721,0.478846,0.376609,0.855455,1
1421,brettge01,George Brett,11625,10349,1583,3154,665,137,317,1596,1096,908,0.304764,0.487390,0.369288,0.856678,1
1156,boggswa01,Wade Boggs,10740,9180,1513,3010,578,61,118,1014,1412,745,0.327887,0.442702,0.414994,0.857695,1
2762,cronijo01,Joe Cronin,8840,7579,1231,2285,517,118,170,1431,1060,702,0.301491,0.468136,0.389600,0.857736,1
6098,irvinmo01,Monte Irvin,2893,2499,367,731,97,31,99,445,351,221,0.292517,0.474990,0.383148,0.858138,1
2488,combsea01,Earle Combs,6514,5750,1184,1866,309,154,58,628,674,283,0.324522,0.462087,0.396894,0.858981,1
5332,hartnga01,Gabby Hartnett,7297,6432,867,1912,399,64,236,1190,704,698,0.297264,0.489272,0.369771,0.859044,1
13232,vaughar01,Arky Vaughan,7722,6623,1173,2104,357,128,96,926,938,278,0.317681,0.453722,0.405864,0.859586,1
2873,cuyleki01,Kiki Cuyler,8100,7161,1300,2300,396,158,128,1068,678,756,0.321184,0.474235,0.386625,0.860860,1
1872,camparo01,Roy Campanella,4687,4096,616,1132,176,18,241,839,518,491,0.276367,0.504639,0.360455,0.865094,1
8447,medwijo01,Joe Medwick,8143,7635,1198,2471,540,113,205,1386,438,551,0.323641,0.504519,0.362390,0.866909,1
3230,dickebi01,Bill Dickey,7065,6305,930,1969,343,72,202,1208,679,286,0.312292,0.485646,0.381896,0.867542,1
1268,bottoji01,Jim Bottomley,8353,7472,1176,2311,466,151,219,1433,661,593,0.309288,0.500000,0.368762,0.868762,1
3301,dobyla01,Larry Doby,6085,5156,930,1457,231,52,247,935,848,975,0.282583,0.491272,0.386150,0.877422,1
13466,wanerpa01,Paul Waner,10766,9460,1627,3152,607,192,113,1326,1093,376,0.333192,0.473784,0.404400,0.878184,1
10881,robinja02,Jackie Robinson,5804,4877,947,1518,274,54,137,734,742,290,0.311257,0.473857,0.409123,0.882980,1
8046,matheed01,Eddie Mathews,9833,8311,1461,2249,345,67,498,1414,1403,1458,0.270605,0.508001,0.375421,0.883422,1
6707,killeha01,Harmon Killebrew,9800,8116,1277,2077,288,24,571,1578,1559,1696,0.255914,0.508379,0.375918,0.884297,1
4463,gehrich01,Charlie Gehringer,10244,8859,1774,2838,574,146,184,1440,1194,375,0.320352,0.480415,0.404097,0.884513,1
4777,gosligo01,Goose Goslin,9829,8658,1481,2735,501,173,248,1618,953,587,0.315893,0.499653,0.387297,0.886950,1
12252,stargwi01,Willie Stargell,9027,7927,1194,2232,423,55,475,1540,937,1936,0.281569,0.528573,0.360169,0.888742,1
8227,mccovwi01,Willie McCovey,9692,8197,1229,2211,353,46,521,1556,1346,1550,0.269733,0.514701,0.374509,0.889210,1
2404,cochrmi01,Mickey Cochrane,6209,5169,1041,1652,333,64,119,837,858,216,0.319598,0.477849,0.419254,0.897102,1
5085,hafeych01,Chick Hafey,5115,4625,775,1465,340,67,164,838,372,477,0.316757,0.525622,0.371769,0.897391,1
12730,terrybi01,Bill Terry,7108,6427,1119,2193,374,112,154,1084,535,452,0.341217,0.506146,0.392627,0.898773,1
4932,griffke02,Ken Griffey Jr.,11304,9801,1662,2781,524,38,630,1836,1312,1779,0.283747,0.537802,0.369511,0.907314,1
11493,schmimi01,Mike Schmidt,10062,8352,1506,2234,408,59,548,1595,1507,1883,0.267481,0.527299,0.380251,0.907550,1
11835,simmoal01,Al Simmons,9519,8759,1507,2929,538,149,307,1843,619,744,0.334399,0.534993,0.380315,0.915307,1
12055,snidedu01,Duke Snider,8021,6978,1224,2070,349,84,391,1298,941,1202,0.296647,0.538836,0.380379,0.919215,1
10084,piazzmi01,Mike Piazza,7745,6911,1048,2127,344,8,427,1335,759,1113,0.307770,0.545218,0.376501,0.921719,1
6783,kleinch01,Chuck Klein,7171,6487,1167,2076,398,74,300,1204,601,520,0.320025,0.542932,0.378820,0.921752,1
10878,robinfr02,Frank Robinson,11454,9748,1796,2855,514,71,571,1779,1396,1485,0.292881,0.535905,0.388670,0.924575,1
445,averiea01,Earl Averill,7221,6353,1222,2019,401,128,238,1165,780,520,0.317803,0.533606,0.395200,0.928806,1
1,aaronha01,Henry Aaron,13666,12121,2128,3703,614,96,740,2243,1372,1357,0.305503,0.555152,0.374276,0.929429,1
6381,jonesch06,Chipper Jones,10614,8984,1617,2726,549,38,468,1623,1512,1409,0.303428,0.529274,0.401093,0.930367,1
9568,ortizda01,David Ortiz,10091,8640,1419,2472,632,19,541,1767,1319,1750,0.286111,0.551505,0.379522,0.931027,1
5002,guerrvl01,Vladimir Guerrero,9059,8155,1328,2590,477,46,449,1496,737,985,0.317597,0.552544,0.378629,0.931173,1
7959,martied01,Edgar Martinez,8674,7213,1219,2247,514,15,309,1261,1283,1202,0.311521,0.515458,0.417802,0.933260,1
8144,mayswi01,Willie Mays,12217,10634,2013,3195,515,132,642,1864,1440,1504,0.300451,0.554824,0.383317,0.938141,1
13903,wilsoha01,Hack Wilson,5555,4760,885,1460,266,67,244,1063,672,714,0.306723,0.544538,0.394718,0.939255,1
6726,kinerra01,Ralph Kiner,6256,5205,971,1451,216,39,369,1016,1011,754,0.278770,0.547935,0.397951,0.945886,1
9623,ottme01,Mel Ott,11348,9454,1856,2876,487,72,511,1870,1721,901,0.304210,0.533108,0.414717,0.947824,1
495,bagweje01,Jeff Bagwell,9431,7797,1517,2314,488,32,449,1529,1401,1558,0.296781,0.540336,0.407616,0.947952,1
12797,thomeji01,Jim Thome,10313,8422,1583,2328,451,26,612,1699,1747,2548,0.276419,0.554144,0.401862,0.956006,1
8734,mizejo01,Johnny Mize,7370,6442,1118,2011,367,84,359,1336,857,527,0.312170,0.562403,0.397225,0.959628,1
13408,walkela01,Larry Walker,8030,6907,1352,2160,471,62,383,1311,913,1231,0.312726,0.565224,0.400224,0.965448,1
3097,delahed01,Ed Delahanty,1332,1172,231,422,92,31,19,222,139,71,0.360068,0.540102,0.432678,0.972780,1
12779,thomafr04,Frank Thomas,10075,8199,1494,2468,495,12,521,1704,1667,1397,0.301012,0.554946,0.419099,0.974044,1
9105,musiast01,Stan Musial,12538,10820,1923,3573,716,176,467,1922,1579,691,0.330222,0.558410,0.416333,0.974744,1
7858,mantlmi01,Mickey Mantle,9690,7924,1641,2351,332,69,528,1484,1694,1690,0.296694,0.555906,0.419285,0.975191,1
3271,dimagjo01,Joe DiMaggio,7672,6821,1389,2215,390,131,361,1539,790,370,0.324732,0.579094,0.398459,0.977553,1
4874,greenha01,Hank Greenberg,6098,5194,1047,1628,379,71,331,1274,853,846,0.313439,0.604929,0.411842,1.016771,1
4121,foxxji01,Jimmie Foxx,9676,8133,1751,2645,458,125,534,1919,1458,1311,0.325218,0.609246,0.428571,1.037818,1
4464,gehrilo01,Lou Gehrig,9665,8001,1889,2721,534,164,493,1996,1512,795,0.340082,0.632671,0.447641,1.080312,1
13864,willite01,Ted Williams,9598,7566,1768,2592,514,71,510,1806,1970,696,0.342585,0.631509,0.479516,1.111026,1
11194,ruthba01,Babe Ruth,10624,8400,2173,2872,506,137,714,2215,2063,1331,0.341905,0.689762,0.473925,1.163687,1

In [129]:
career.isnull().values.any()

False

In [138]:
hank_row = career[career['ID'] == 'aaronha01']

cols = ['PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'BB', 'SO', 'AVG', 'SLG', 'OBP', 'OPS']
XX = hank_row[cols]

XX

,PA,AB,R,H,2B,3B,HR,RBI,BB,SO,AVG,SLG,OBP,OPS
1,13666,12121,2128,3703,614,96,740,2243,1372,1357,0.305503,0.555152,0.374276,0.929429

### Converting to X and y

In [131]:
y = career[career.columns[-1]]
y = y.values
y

array([0, 1, 0, ..., 0, 0, 0])

In [132]:
# remove the HOF inductee column, and the string-based fields
num = career.shape[1]
X = career[career.columns[2:num-1]]
X = X.values
X

# X = career[career.columns[2:num-5]]
# X = X.values
# X

array([[5.00000000e+00, 4.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.36660000e+04, 1.21210000e+04, 2.12800000e+03, ...,
        5.55152215e-01, 3.74276292e-01, 9.29428507e-01],
       [1.04500000e+03, 9.44000000e+02, 9.90000000e+01, ...,
        3.27330508e-01, 2.90821256e-01, 6.18151765e-01],
       ...,
       [8.00000000e+00, 7.00000000e+00, 1.00000000e+00, ...,
        4.28571429e-01, 3.75000000e-01, 8.03571429e-01],
       [5.45000000e+02, 4.91000000e+02, 4.00000000e+01, ...,
        2.76985743e-01, 2.75142315e-01, 5.52128058e-01],
       [1.56000000e+02, 1.33000000e+02, 4.00000000e+00, ...,
        1.72932331e-01, 1.85714286e-01, 3.58646617e-01]])

### Visualization(s)

??? Before and after bar graphs?

## Model Selection

### Logistic Regression

In [133]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

# Split data into training and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 20)

# Import logistic regression 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import log_loss

# Build a logstic regression object
LogReg = LogisticRegression(solver = 'newton-cg')

# Train(fit) model
LogReg.fit(X_train, y_train)

# Predict the data
y_train_predict = LogReg.predict(X_train)
y_test_predict = LogReg.predict(X_test)

# Count percentage of correct predictions
print("The performance of the model")
print("--------------------------------------")
print('Log loss of the model for training set: %.3f' % log_loss(y_train,y_train_predict))
print('Log loss of the model for test set: %.3f' % log_loss(y_test,y_test_predict))

The performance of the model
--------------------------------------
Log loss of the model for training set: 0.315
Log loss of the model for test set: 0.351

In [140]:
LogReg.predict(XX.values)

array([0])

In [134]:
# Count percentage of correct predictions
print("The performance of the model:")
print("------------------------------")

# Confusion Matrix
from sklearn.metrics import confusion_matrix
print('Confusion matrix for training set')
print(confusion_matrix(y_train,y_train_predict))

print('Confusion matrix for test set')
print(confusion_matrix(y_test, y_test_predict),'\n')

# Accuracy Score
from sklearn.metrics import accuracy_score
print('Accuracy of the model for training set: %.3f' % accuracy_score(y_train,y_train_predict))
print('Accuracy of the model for test set: %.3f\n' % accuracy_score(y_test,y_test_predict))

# Precision score
from sklearn.metrics import precision_score
print('Precision of the model for training set: %.3f' % precision_score(y_train,y_train_predict))
print('Precision of the model for test set: %.3f\n' % precision_score(y_test,y_test_predict))

# Recall score
from sklearn.metrics import recall_score
print('Recall of the model for training set: %.3f' % recall_score(y_train,y_train_predict))
print('Recall of the model for test set: %.3f\n' % recall_score(y_test,y_test_predict))

# F1 Score
from sklearn.metrics import f1_score
print('F1-measure of the model for training set: %.3f' % f1_score(y_train,y_train_predict))
print('F1-measure of the model for test set: %.3f\n' % f1_score(y_test,y_test_predict))

# AUC score
from sklearn.metrics import roc_auc_score
print('AUC score of the model for training set: %.3f' % roc_auc_score(y_train,y_train_predict))
print('AUC score of the model for test set: %.3f\n' % roc_auc_score(y_test,y_test_predict))
      
# Log loss
print('Log loss of the model for training set: %.3f' % log_loss(y_train,y_train_predict))
print('Log loss of the model for test set: %.3f\n' % log_loss(y_test,y_test_predict))

The performance of the model:
------------------------------
Confusion matrix for training set
[[11257    12]
 [   92    50]]
Confusion matrix for test set
[[2816    3]
 [  26    8]]

Accuracy of the model for training set: 0.991
Accuracy of the model for test set: 0.990

Precision of the model for training set: 0.806
Precision of the model for test set: 0.727

Recall of the model for training set: 0.352
Recall of the model for test set: 0.235

F1-measure of the model for training set: 0.490
F1-measure of the model for test set: 0.356

AUC score of the model for training set: 0.676
AUC score of the model for test set: 0.617

Log loss of the model for training set: 0.315
Log loss of the model for test set: 0.351

In [135]:
 import matplotlib.pyplot as plt

###